version: "3"
services:
#pull and run sonarqube and jenkins on the same network
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    #specify network for sonar
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
    #specify network for jenkins
    networks:
      - mynetwork
networks:
  mynetwork:
